"""Verify the add-on archive layout without installing Torch or building binaries."""
import json
from pathlib import Path
import sys
import tempfile
import types
import unittest
from tests.depth_fixture import depth_test_case
from unittest import mock
import zipfile

from dlss5tool import mod_paths
from scripts import build_enhancement


@depth_test_case
class EnhancementBuildTests(unittest.TestCase):
    def test_zip_extracts_beside_app_and_is_detected_with_no_path_configuration(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            source = root / 'source'
            (source / 'depth_anything_v2').mkdir(parents=True)
            (source / 'depth_anything_v2/dpt.py').touch()
            license_path = root / 'fixture-license.txt'
            license_path.write_text('Test fixture only')
            weights = root / 'fixture.pth'
            weights.write_bytes(b'fixture weights')
            output = root / 'dist'
            def fake_build(command, **kwargs):
                folder = Path(command[command.index('--distpath') + 1]) / 'enhancement'
                (folder / '_internal').mkdir(parents=True)
                (folder / 'guidance_worker.exe').touch()
                (folder / '_internal/python313.dll').touch()
            arguments = ['build_enhancement.py', '--depth-source', str(source),
                '--depth-license', str(license_path), '--output', str(output), '--zip',
                '--depth-weights', str(weights), '--encoder', 'vits', '--weights-notice', str(license_path)]
            with mock.patch.object(sys, 'argv', arguments), mock.patch.dict(sys.modules,
                    {'torch': types.SimpleNamespace(version=types.SimpleNamespace(cuda=None))}), \
                    mock.patch.object(build_enhancement.importlib.metadata, 'version', return_value='fixture'), \
                    mock.patch.object(build_enhancement.subprocess, 'run', side_effect=fake_build):
                build_enhancement.main()
            destination = root / 'app'
            with zipfile.ZipFile(output / 'enhancement.zip') as archive:
                names = archive.namelist()
                self.assertIn('mods/enhancement/enhancement.json', names)
                self.assertIn('mods/enhancement/models/depth_anything_v2_vits.pth', names)
                self.assertFalse(any(name.startswith(('build/', 'enhancement/')) for name in names))
                archive.extractall(destination)  # archive was generated by this test
            with mock.patch.object(mod_paths, 'app_root', return_value=destination):
                self.assertEqual(mod_paths.depth_encoder({}), 'vits')
                self.assertTrue(mod_paths.guidance_files({'guidance_mode': 2})['worker'])
            payload = json.loads((output / 'mods/enhancement/enhancement.json').read_text())
            self.assertEqual(payload['protocol'], mod_paths.GUIDANCE_PROTOCOL)
